/**
 * TypeScript declarations for the Rust NAPI-RS native module.
 * These are auto-generated by napi-rs at build time, but we provide
 * manual declarations for development convenience.
 */

// --- Hasher ---
export function sha256Hash(content: string): string;
export function sha256HashFile(filePath: string): string;
export interface FileHash {
  path: string;
  hash: string;
}
export function sha256HashFiles(filePaths: string[]): FileHash[];

// --- Merkle Tree ---
export interface MerkleNode {
  path: string;
  hash: string;
  isFile: boolean;
  children: string[];
}

export interface MerkleDiff {
  added: string[];
  removed: string[];
  modified: string[];
}

export interface FileHashEntry {
  path: string;
  hash: string;
}

export function buildMerkleTree(fileHashes: FileHashEntry[]): MerkleNode[];
export function diffMerkleTrees(
  oldNodes: MerkleNode[],
  newNodes: MerkleNode[]
): MerkleDiff;
export function getRootHash(nodes: MerkleNode[]): string | null;

// --- Scanner ---
export function scanDirectory(
  rootPath: string,
  extensions: string[]
): string[];
export function getRelativePath(
  rootPath: string,
  filePath: string
): string | null;
